service: integration-api-arnel

frameworkVersion: '3'

configValidationMode: error
useDotenv: true

package:
  individually: true

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  stage: ${opt:stage, "dev"}
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
        - "dynamodb:*"
        Resource: "arn:aws:dynamodb:${aws:region}:*:table/integration-person-arnel"
  environment:
      APP_AUTH_BASE_URL: ${env:APP_AUTH_BASE_URL}
      APP_HUB_BASE_URL: ${env:APP_HUB_BASE_URL}
      APP_ID: ${env:APP_ID}
      APP_SECRET: ${env:APP_SECRET}
      APP_USERNAME: ${env:APP_USERNAME}
      APP_PASSWORD: ${env:APP_PASSWORD}
functions:
  app:
    package:
      patterns:
        - 'src/**'
        - '!requirements.txt'
        - '!package.json'
        - '!package-lock.json'
        - '!.serverless/**'
        - '!venv/**'
        - '!env/**'
        - '!envwin/**'
        - '!node_modules/**'
    handler: core.main.handler
    name: integration-function-arnel
    description: Integration API
    timeout: 29
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: get
          path: /
      - http:
          method: any
          path: /{proxy+}

resources:
  Resources:
    IntegrationPersonTableArnel:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: integration-person-arnel
        AttributeDefinitions:
          - AttributeName: entryId
            AttributeType: S
        KeySchema:
          - AttributeName: entryId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1